#!/usr/bin/env python3
"""FCM Hosts 更新脚本

从 GitHub 下载 FCM hosts 模板，合并到 Mihomo (Clash Meta) 配置文件 android.yaml 中。
不修改源文件任何内容（包括注释和格式），仅追加/更新 hosts 段。

用法：由系统 crontab 调度，例如：
    0 0,12 * * * cd /path/to/fcmhosts && python updater.py
"""

import logging
import re
import sys
from datetime import datetime
from pathlib import Path

import requests

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

FCM_HOSTS_URL = (
    "https://raw.githubusercontent.com/cagedbird043/fcm-hosts-next/main/fcm_ipv4.hosts"
)
ANDROID_YAML_URL = "http://index.home.arpa/mihomo/phone/android.yaml"
ANDROID_YAML_PATH = Path("android_fcm.yaml")


def download_text(url: str, label: str = "") -> str:
    """通过 HTTP 下载文本内容。"""
    try:
        resp = requests.get(url, timeout=30)
        resp.raise_for_status()
        return resp.text
    except requests.RequestException as e:
        logger.error("下载%s失败 [%s]: %s", label, url, e)
        sys.exit(1)


def parse_hosts_text(text: str) -> dict[str, str]:
    """解析 hosts 格式文本 -> {域名: IP} 字典。"""
    hosts: dict[str, str] = {}
    for line in text.strip().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        line = line.split("#")[0].strip()
        parts = line.split()
        if len(parts) >= 2:
            hosts[parts[1]] = parts[0]
    return hosts


def format_hosts_yaml(hosts: dict[str, str]) -> str:
    """将 hosts 字典格式化为 YAML hosts: 段文本。"""
    lines = ["hosts:"]
    for domain, ip in hosts.items():
        lines.append(f"  {domain}: {ip}")
    return "\n".join(lines) + "\n"


def merge_hosts_to_text(original: str, hosts_block: str) -> str:
    """将 hosts 段合并到原始 YAML 文本中。"""
    pattern = re.compile(r"^hosts:.*?(?=^[a-zA-Z0-9]|\Z)", re.MULTILINE | re.DOTALL)
    if pattern.search(original):
        logger.info("检测到已有 hosts 段，将替换")
        return pattern.sub(hosts_block.rstrip("\n"), original)
    else:
        logger.info("未检测到 hosts 段，将在末尾追加")
        if not original.endswith("\n"):
            original += "\n"
        return original + "\n" + hosts_block


def prepend_timestamp(text: str) -> str:
    """在 YAML 开头插入生成时间戳注释。"""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = f"# Generated by fcmhosts at {ts}\n"
    return header + text


def main() -> None:
    """主流程：下载 hosts + 下载配置 → 合并 → 写回。"""
    logger.info("开始更新 FCM hosts...")

    hosts_text = download_text(FCM_HOSTS_URL, label="hosts")
    new_hosts = parse_hosts_text(hosts_text)
    logger.info("解析到 %d 条 hosts 记录", len(new_hosts))

    if not new_hosts:
        logger.warning("未解析到任何 hosts 记录，跳过更新")
        sys.exit(1)

    original_yaml = download_text(ANDROID_YAML_URL, label="配置")
    hosts_block = format_hosts_yaml(new_hosts)
    merged = merge_hosts_to_text(original_yaml, hosts_block)
    merged = prepend_timestamp(merged)

    ANDROID_YAML_PATH.write_text(merged, encoding="utf-8")
    logger.info("FCM hosts 更新完成，已写入 %s", ANDROID_YAML_PATH)


if __name__ == "__main__":
    main()